In [1]:
import numpy as np


In [2]:
list = [[1,2,3,4,5],[4,5,6,7,8]]

In [3]:
# numpy aray
np_array = np.array(list)

In [4]:
np_array

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [5]:
type(np_array)

numpy.ndarray

In [6]:
# to check dimension of numpy array
np_array.shape

(2, 5)

In [34]:
np_array.ndim

2

In [35]:
# to check dtype of array
np_array.dtype

dtype('int64')

In [7]:
# slicing and accesing numpy array
np_array[0,0]

1

In [8]:
np_array[1,2]

6

In [10]:
# numpy matrix : it is a subset of numpy array
np_matrix = np.matrix(list)

In [11]:
np_matrix

matrix([[1, 2, 3, 4, 5],
        [4, 5, 6, 7, 8]])

In [12]:
type(np_matrix)

numpy.matrix

In [13]:
# Concept of swallow copy: if we create a copy and make changes in it, the other will automatically change
swallow_copy = np_array

In [14]:
swallow_copy

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [15]:
swallow_copy[0,0] = 100

In [16]:
swallow_copy

array([[100,   2,   3,   4,   5],
       [  4,   5,   6,   7,   8]])

In [17]:
np_array

array([[100,   2,   3,   4,   5],
       [  4,   5,   6,   7,   8]])

In [20]:
# deep copy : where we create a copy in another location and then the changes dont occur in the copied variable

deep_copy = np.copy(np_array)

In [21]:
deep_copy

array([[100,   2,   3,   4,   5],
       [  4,   5,   6,   7,   8]])

In [22]:
deep_copy[0,0] = 1

In [23]:
deep_copy

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [24]:
# IT DOESNT CHANGES
np_array

array([[100,   2,   3,   4,   5],
       [  4,   5,   6,   7,   8]])

In [27]:
# fromfunction : used to generate arrays as per the logic stated

np.fromfunction(lambda i,j : i==j ,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
np.fromfunction(lambda i,j : i*j , (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [31]:
np.fromfunction(lambda i,j : i**2 , (3,3))

array([[0., 0., 0.],
       [1., 1., 1.],
       [4., 4., 4.]])

In [32]:
#fromiter: generate numpy array using iterable

iterable = (i*i for i in range(5))
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [33]:
#fromstring

np.fromstring('234 234',sep=' ')

array([234., 234.])

In [36]:
#arange : to create data with jump of float number

np.arange(2.3,3.3,.3)

array([2.3, 2.6, 2.9, 3.2])

In [38]:
# linspace: create data using a data range

np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [39]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [44]:
# 3d array with 4x2 array x3 times
d3_array = np.zeros((3,4,2))

In [45]:
d3_array

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [46]:
d3_array.ndim

3

In [49]:
# 4d array : 3x4 array x3 times x4 times
d4_array = np.zeros((4,3,3,4))

In [50]:
d4_array

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]

In [51]:
d4_array.ndim

4

In [52]:
# create array with 1s

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones((3,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [54]:
#empty funtion

np.empty((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [55]:
# eye : to create identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
# logspace

np.logspace(2,5,base = 2)

array([ 4.        ,  4.17340372,  4.35432466,  4.54308869,  4.74003581,
        4.94552078,  5.15991371,  5.38360077,  5.61698488,  5.8604864 ,
        6.11454394,  6.37961511,  6.65617737,  6.94472885,  7.24578931,
        7.55990103,  7.88762977,  8.22956587,  8.58632521,  8.9585504 ,
        9.3469119 ,  9.75210923, 10.17487225, 10.61596243, 11.07617429,
       11.55633675, 12.05731471, 12.58001053, 13.1253657 , 13.69436252,
       14.28802588, 14.90742511, 15.55367586, 16.22794219, 16.93143859,
       17.66543222, 18.43124515, 19.23025679, 20.06390632, 20.93369534,
       21.84119052, 22.78802646, 23.77590863, 24.8066164 , 25.88200631,
       27.00401538, 28.17466459, 29.39606253, 30.67040921, 32.        ])

In [59]:
#random data generation

#randn: it will produce data as per standard normal distribution with mean = 0 and std dev =1

rand_array = np.random.randn(3,4)

In [61]:
import pandas as pd
pd.DataFrame(rand_array)

0         1         2         3
0 -1.879100 -0.791575 -0.484778  0.684948
1 -0.044877  1.689520 -0.715040  0.731153
2 -0.300338 -0.403914  0.210167 -0.944660

In [62]:
#rand: it will be random not neccesary to be std normal distribution

np.random.rand(3,4)

array([[0.29629716, 0.9401833 , 0.77374232, 0.97950363],
       [0.56969082, 0.96535611, 0.63531077, 0.84307912],
       [0.36678783, 0.0436982 , 0.41786466, 0.73198172]])

In [65]:
#randint: returns only integers

randint_array = np.random.randint(1,110,(3,4))

In [72]:
randint_array

array([[42, 35, 83, 69],
       [91,  2, 61, 21],
       [14, 42,  4, 17]])

In [66]:
#reshape: to reshape anydata

randint_array.reshape(6,2)

array([[42, 35],
       [83, 69],
       [91,  2],
       [61, 21],
       [14, 42],
       [ 4, 17]])

In [76]:
#slicing

randint_array[1:3,1]

array([ 2, 42])

In [78]:
randint_array[randint_array>50]

array([83, 69, 91, 61])

In [79]:
randint_array[1:3,[1,2]]

array([[ 2, 61],
       [42,  4]])

In [80]:
# lets see some matrix operation

arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [83]:
arr1

array([[2, 1, 1],
       [2, 1, 2],
       [1, 2, 1]])

In [84]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [1, 2, 2]])

In [81]:
arr1+arr2

array([[4, 3, 3],
       [4, 2, 3],
       [2, 4, 3]])

In [82]:
# this will give index multiplication not matrix multiplication

arr1*arr2

array([[4, 2, 2],
       [4, 1, 2],
       [1, 4, 2]])

In [85]:
# for matrix multiplication

arr1@arr2

array([[7, 7, 7],
       [8, 9, 9],
       [7, 6, 6]])

In [86]:
# div by zero doesnt gives error

arr1/0

/var/folders/lw/97p97tps55bddkd_rvpmy8400000gn/T/ipykernel_1252/3825591185.py:3: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [88]:
arr1**2

array([[4, 1, 1],
       [4, 1, 4],
       [1, 4, 1]])

In [90]:
# numpy broadcasting

arr3 = np.zeros((3,4))


In [91]:
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
row = np.array([1,2,3,4])

In [93]:
# this addition does row by row broadcasting of array   

arr3+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [102]:
# to do col wise broadcasting

col = np.array([[1,2,3]])

In [103]:
col

array([[1, 2, 3]])

In [104]:
col.T

array([[1],
       [2],
       [3]])

In [106]:
# now it does col by col broadcasting

arr3+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])