In [1]:
import numpy as np

In [25]:
arr = np.random.randint(1,10,(3,4))

In [26]:
arr

array([[7, 1, 1, 5],
       [4, 8, 3, 2],
       [8, 3, 1, 7]])

In [27]:
# mathematical operations
np.mean(arr)

4.166666666666667

In [28]:
np.median(arr)

3.5

In [29]:
np.tanh(arr)

array([[0.99999834, 0.76159416, 0.76159416, 0.9999092 ],
       [0.9993293 , 0.99999977, 0.99505475, 0.96402758],
       [0.99999977, 0.99505475, 0.76159416, 0.99999834]])

In [30]:
np.max(arr)

8

In [31]:
np.std(arr)

2.6404965862924765

In [5]:
# flatten

arr.flatten()

array([7, 3, 2, 9, 7, 4, 9, 1, 6, 2, 5, 1])

In [6]:
arr1 = np.array([1,2,3,4])

In [7]:
#expand_dims: it will icrease the dimension of the existing array by 1

np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [8]:
# squeeze

data = np.array([[1],[2],[3]])

In [9]:
data

array([[1],
       [2],
       [3]])

In [13]:
data = np.squeeze(data)

In [18]:
data = np.repeat(data,3)

In [20]:
np.roll(data,3)

array([3, 3, 3, 1, 1, 1, 2, 2, 2])

In [21]:
np.diag(data)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 3]])

In [22]:
#numpy string function

arr = np.array(['abhi','jain'])

In [23]:
np.char.upper(arr)

array(['ABHI', 'JAIN'], dtype='<U4')

In [24]:
np.char.title(arr)

array(['Abhi', 'Jain'], dtype='<U4')

In [32]:
# Sort, Search and Counting Functions

arr = np.array([4,2,5,6,78,65,4,97,88])

In [33]:
# sort array
np.sort(arr)

array([ 2,  4,  4,  5,  6, 65, 78, 88, 97])

In [34]:
# search at what place value be placed in sorted array

np.searchsorted(arr,45)

4

In [35]:
arr1 = np.array([0,0,0,33,44,55,66,0,0,0])

In [37]:
np.count_nonzero(arr1)

4

In [38]:
np.where(arr>6)

(array([4, 5, 7, 8]),)

In [40]:
np.extract(arr>6,arr)

array([78, 65, 97, 88])